services:
  server:
    build:
      context: ./
      dockerfile: ./cmd/server/Dockerfile
    volumes:
      - broker-db:/data
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build:
      context: ./
      dockerfile: ./cmd/worker/Dockerfile
    volumes:
      - broker-db:/data

volumes:
  broker-db:
    driver: local